stocks:
  - symbol: QQQ
    name: Invesco QQQ Trust
    type: ETF
    alerts:
      price_change_threshold: 2.0  # 2% 價格變動觸發警報
      rsi_oversold: 30
      rsi_overbought: 70
  
  - symbol: SMH
    name: VanEck Semiconductor ETF
    type: ETF
    alerts:
      price_change_threshold: 2.0
      rsi_oversold: 30
      rsi_overbought: 70
  
  - symbol: TSLA
    name: Tesla Inc.
    type: Stock
    alerts:
      price_change_threshold: 3.0
      rsi_oversold: 30
      rsi_overbought: 70
  
  - symbol: NVDA
    name: NVIDIA Corporation
    type: Stock
    alerts:
      price_change_threshold: 3.0
      rsi_oversold: 30
      rsi_overbought: 70


